BeerOverFlow.Web/Controllers/BeersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BeerOverFlow.Services.Contracts;
using AutoMapper;
using BeerOverFlow.Web.Models;
using BeerOverFlow.Services.DTOs;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using BeerOverFlow.Models;
using Microsoft.AspNetCore.Identity;

namespace BeerOverFlow.Web.Controllers
{
    public class BeersController : Controller
    {
        private readonly IBeerService _beerService;
        private readonly IMapper _mapper;
        private readonly IStyleService _styleService;
        private readonly IBreweryService _breweryService;
        private readonly ICountryService _countryService;
        private readonly SignInManager<User> _signInManager;

        public BeersController(SignInManager<User> signInManager, IBeerService service, IMapper mapper, IBreweryService breweryService, IStyleService styleService, ICountryService countryService)
        {
            this._beerService = service;
            this._mapper = mapper;
            this._breweryService = breweryService;
            this._styleService = styleService;
            this._countryService = countryService;
            this._signInManager = signInManager;
        }

        public IActionResult Index()
        {
            return View( _beerService.GetAllBeers());
        }

        [HttpGet]
        public IActionResult FilterByCountry()
        {
            var vm = new FilterViewModel();
            vm.SearchText = "";
            vm.SearchResults = new List<BeerDTO>();
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> FilterByCountry(FilterViewModel model)
        {
            var result = await _beerService.FilterBeersByCountryAsync(model.SearchText);
            model.SearchResults = result;
            return View(model);
        }

        [HttpGet]
        public IActionResult FilterByStyle()
        {
            var vm = new FilterViewModel();
            vm.SearchText = "";
            vm.SearchResults = new List<BeerDTO>();
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> FilterByStyle(FilterViewModel model)
        {
            var result = await _beerService.FilterBeersByStyleAsync(model.SearchText);
            model.SearchResults = result;
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> SortByABV()
        {
            var result = await _beerService.SortBeerByABVAsync();
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> SortByName()
        {
            var result = await _beerService.SortBeerByNameAsync();
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> SortByRating()
        {
            var result = await _beerService.SortBeerByRatingAsync();
            return View(result);
        }

        public IActionResult Details(int id)
        {
            var beer =  _beerService.GetBeer(id);
            return View(beer);
        }

        public IActionResult Create()
        {
            if (!_signInManager.IsSignedIn(User))
            {
                Response.Redirect("http://localhost:53299/Identity/Account/Login");
            }
            ViewData["BreweryId"] = new SelectList( _breweryService.GetAllBreweries(), "Id", "Name");
            ViewData["StyleId"] = new SelectList( _styleService.GetAllStyles(), "Id", "Name");
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BeerViewModel beer)
        {

            var beerDTO = _mapper.Map<BeerDTO>(beer);

            await _beerService.CreateBeerAsync(beerDTO);

            return RedirectToAction(nameof(Index));
        }


        public IActionResult Edit(int id)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                Response.Redirect("http://localhost:53299/Identity/Account/Login");
            }

            var beer =  _beerService.GetBeer(id);

            ViewData["BreweryId"] = new SelectList( _breweryService.GetAllBreweries(), "Id", "Name");
            ViewData["StyleId"] = new SelectList( _styleService.GetAllStyles(), "Id", "Name");

            return View(beer);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BeerViewModel beerViewModel)
        {
            var beerDTO = _mapper.Map<BeerDTO>(beerViewModel);

            await _beerService.UpdateBeerAsync(id, beerDTO);

            return RedirectToAction(nameof(Index));
        }



        public IActionResult Delete(int id)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                Response.Redirect("http://localhost:53299/Identity/Account/Login");
            }

            var beer =  _beerService.GetBeer(id);

            return View(beer);
        }


        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var beer = await _beerService.DeleteBeerAsync(id);

            return RedirectToAction(nameof(Index));
        }
      
    }
}

BeerOverFlow.Web/Controllers/BreweriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeerOverFlow.DataBase;
using BeerOverFlow.Models;
using BeerOverFlow.Services.Contracts;
using AutoMapper;
using BeerOverFlow.Web.Models;
using BeerOverFlow.Services.DTOs;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace BeerOverFlow.Web.Controllers
{
    public class BreweriesController : Controller
    {
        private readonly ICountryService _countryService;
        private readonly IBreweryService _service;
        private readonly IMapper _mapper;
        private readonly SignInManager<User> _signInManager;

        public BreweriesController(SignInManager<User> signInManager, IBreweryService service, IMapper mapper, ICountryService countryService)
        {
            _service = service;
            _mapper = mapper;
            _countryService = countryService;
            this._signInManager = signInManager;
        }

        // GET: Breweries
        public IActionResult Index()
        {
            return View(_service.GetAllBreweries());
        }

        // GET: Breweries/Details/5
        public IActionResult Details(int id)
        {

            var brewery =  _service.GetBrewery(id);

            return View(brewery);
        }

        // // GET: Breweries/Create
        public async Task<IActionResult> Create()
        {
            if (!_signInManager.IsSignedIn(User))
            {
                Response.Redirect("http://localhost:53299/Identity/Account/Login");
            }
            ViewData["CountryId"] = new SelectList(await _countryService.GetAllCountriesAsync(), "Id", "Name");
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BreweryViewModel breweryViewModel)
        {
            var breweryDTO = _mapper.Map<BreweryDTO>(breweryViewModel);

            await _service.CreateBreweryAsync(breweryDTO);

            return RedirectToAction(nameof(Index));

        }

        // // GET: Breweries/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                Response.Redirect("http://localhost:53299/Identity/Account/Login");
            }

            var brewery =  _service.GetBrewery(id);

            ViewData["CountryId"] = new SelectList(await _countryService.GetAllCountriesAsync(), "Id", "Name");

            return View(brewery);
        }

        // // POST: Breweries/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BreweryViewModel breweryViewModel)
        {
            var breweryDTO = _mapper.Map<BreweryDTO>(breweryViewModel);

            await _service.UpdateBreweryAsync(id, breweryDTO);

            return RedirectToAction(nameof(Index));
        }

        // // GET: Breweries/Delete/5
        public IActionResult Delete(int id)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                Response.Redirect("http://localhost:53299/Identity/Account/Login");
            }

            var brewery = _service.GetBrewery(id);

            return View(brewery);
        }

        // // POST: Breweries/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brewery = await _service.DeleteBreweryAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

BeerOverFlow.Web/Controllers/ReviewsController.cs
using AutoMapper;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BeerOverFlow.Services.Contracts;
using BeerOverFlow.Web.Models;
using BeerOverFlow.Services.DTOs;
using Microsoft.AspNetCore.Identity;
using BeerOverFlow.Models;
using Microsoft.AspNetCore.Authorization;

namespace BeerOverFlow.Web.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly IBeerService _beerService;
        private readonly IReviewService _service;
        private readonly IMapper _mapper;
        private readonly SignInManager<User> _signInManager;

        public ReviewsController(SignInManager<User> signInManager, IBeerService beerService, IReviewService service, IMapper mapper)
        {
            _beerService = beerService;
            _service = service;
            _mapper = mapper;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAllReviewsAsync());
        }

        public async Task<IActionResult> Details(int id)
        {
            var review = await _service.GetReviewAsync(id);

            return View(review);
        }

        public IActionResult Create()
        {
            if (!_signInManager.IsSignedIn(User))
            {
                Response.Redirect("http://localhost:53299/Identity/Account/Login");
            }

            ViewData["BeerId"] = new SelectList( _beerService.GetAllBeers(), "Id", "Name");
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReviewViewModel reviewViewModel)
        {
            var reviewDTO = _mapper.Map<ReviewDTO>(reviewViewModel);

            await _service.CreateReviewAsync(reviewDTO);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                Response.Redirect("http://localhost:53299/Identity/Account/Login");
            }

            var review = await _service.GetReviewAsync(id);

            ViewData["BeerId"] = new SelectList(_beerService.GetAllBeers(), "Id", "Name");

            return View(review);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ReviewViewModel reviewViewModel)
        {
            var reviewDTO = _mapper.Map<ReviewDTO>(reviewViewModel);

            await _service.UpdateReviewAsync(id, reviewDTO);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                Response.Redirect("http://localhost:53299/Identity/Account/Login");
            }

            var review = await _service.GetReviewAsync(id);

            return View(review);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var review = await _service.DeleteReviewAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

BeerOverFlow.Web/Controllers/StylesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeerOverFlow.DataBase;
using BeerOverFlow.Models;
using AutoMapper;
using BeerOverFlow.Services.Contracts;
using BeerOverFlow.Web.Models;
using BeerOverFlow.Services.DTOs;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace BeerOverFlow.Web.Controllers
{
    public class StylesController : Controller
    {
        private readonly IStyleService _service;
        private readonly IMapper _mapper;
        private readonly SignInManager<User> _signInManager;

        public StylesController(SignInManager<User> signInManager, IStyleService service, IMapper mapper)
        {
            _service = service;
            _mapper = mapper;
            _signInManager = signInManager;
        }

        // GET: Styles
        public IActionResult Index()
        {
            return View( _service.GetAllStyles());
        }

        // GET: Styles/Details/5
        public IActionResult Details(int id)
        {
            var style = _service.GetStyle(id);

            return View(style);
        }

        // GET: Styles/Create
        public IActionResult Create()
        {
            if (!_signInManager.IsSignedIn(User))
            {
                Response.Redirect("http://localhost:53299/Identity/Account/Login");
            }

            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(StyleViewModel styleViewModel)
        {
            var styleDTO = _mapper.Map<StyleDTO>(styleViewModel);

            await _service.CreateStyleAsync(styleDTO);

            return RedirectToAction(nameof(Index));
        }

        // GET: Styles/Edit/5
        public IActionResult Edit(int id)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                Response.Redirect("http://localhost:53299/Identity/Account/Login");
            }

            var style = _service.GetStyle(id);
            return View(style);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, StyleViewModel styleViewModel)
        {
            var styleDTO = _mapper.Map<StyleDTO>(styleViewModel);

            await _service.UpdateStyleAsync(id, styleDTO);

            return RedirectToAction(nameof(Index));
        }

        // GET: Styles/Delete/5
        public IActionResult Delete(int id)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                Response.Redirect("http://localhost:53299/Identity/Account/Login");
            }

            var style =  _service.GetStyle(id);

            return View(style);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var country = await _service.DeleteStyleAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

BeerOverFlow.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeerHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style type="text/css">
        body {
            background-image: url(./images/gettyimages-946877514-640x640.jpg);
            background-size: cover;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeerHub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Beers
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Beers" asp-action="Create">Create Beer</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Beers" asp-action="Index">All Beers</a>

                                </div>
                            </div>
                        </li>

                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Countries
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Create">Create Country</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">All Countries</a>
                                </div>
                            </div>
                        </li>

                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Breweries
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Breweries" asp-action="Create">Create Brewery</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Breweries" asp-action="Index">All Breweries</a>
                                </div>
                            </div>
                        </li>

                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Reviews
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Reviews" asp-action="Create">Create Review</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Reviews" asp-action="Index">All Reviews</a>
                                </div>
                            </div>
                        </li>

                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Styles
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Styles" asp-action="Create">Create Style</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Styles" asp-action="Index">All Styles</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BeerOverFlow.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BeerOverFlow.Web/Views/Shared/_sigleBeerPartial.cshtml
@model BeerViewModel

<div class="col-md-4">
        <h5 class="card-title">@Model.Name</h5>
    <img class="align-content-between d-block w-50" 
         img src="~/images/beercard.jpg" alt="">
    <div class="card-body">
        <p class="card-text">@Model.ABV</p>
        <p class="card-text">@Model.Style.Name</p>
        <p class="card-text">@Model.Description</p>
        <a asp-area="" asp-controller="Beers" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary">Find out more</a>
    </div>
</div>

BeerOverFlow.Web/Views/Shared/_singleBreweryPartial.cshtml
@model BreweryViewModel

<div class="col-md-4">
    <img class="align-content-between d-block w-50" img src="~/images/beer.jpg" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.Country.Name</p>
        <a asp-area="" asp-controller="Breweries" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary">Find out more</a>
    </div>
</div>